// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suizholxeqcqfjajznnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aXpob2x4ZXFjcWZqYWp6bm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTA5NjksImV4cCI6MjA2OTYyNjk2OX0.maAu3CgLQNpPHW_UStJPMd-s1Ic8h06zhjNNdKZGaXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});